# Generated by Django 6.1.1 on 2026-09-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=10)),
                ('long_name', models.CharField(max_length=255)),
                ('mode', models.CharField(default='bus', max_length=10)),
            ],
        ),
    ]
