# Generated by Django 6.1.1 on 2026-09-30 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=100)),
                ('stop_id', models.CharField(max_length=50)),
                ('delay_seconds', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_readings', to='routes.route')),
            ],
            options={
                'indexes': [models.Index(fields=['route', 'recorded_at'], name='routes_dela_route_i_4d49b1_idx')],
            },
        ),
    ]
