# Generated by Django 6.1.1 on 2026-09-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_delayreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('record_count', models.IntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
